version: '3.9'

services:
  server:
    image: metr_server:elegancy
    build: .
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - server_volume:/home/app/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
  redis:
      image: "redis:alpine"
      expose:
        - 6379
      volumes:
        - redis_volume:/data  


volumes:
  postgres_volume:
  redis_volume:
  server_volume:
