version: '3.7'

services:
  daphne-server:
    image: cherniaev/metr:0.1.2
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - daphne_server_volume:/home/app/
      - static_content:/home/app/web/build/

  postgres-db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE

  redis-db:
      image: "redis:alpine"
      expose:
        - 6379
      volumes:
        - redis_db_volume:/data  

volumes:
  daphne_server_volume:
  postgres_db_volume:
  redis_db_volume:
  static_content: