version: '3.7'

services:
  daphne-server:
    build: .
    command: daphne -b host.docker.internal -p 8000 server.asgi:application
    expose:
      - 8000
    env_file:
      - .env
    extra_host:
      - host.docker.internal
    environment:
      - DJANGO_SETTINGS_MODULE=server.settings
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - daphne_server_volume:/home/app/

  postgres-db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
      
  redis-db:
      image: "redis:alpine"
      expose:
        - 6379
      volumes:
        - redis_db_volume:/data  

volumes:
  daphne_server_volume:
  postgres_db_volume:
  redis_db_volume:
