version: '3.3'

services:
  server:
    image: metr_server:elegancy
    build: .
    command: daphne -b 0.0.0.0 -p 8000 server.asgi:application
    expose:
      - 8000
    env_file:
      - .env
    volumes:
      - main_server_volume:/home/app/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/home/postgresql/
    environment:
      - POSTGRES_USER=$SQL_USER
      - POSTGRES_PASSWORD=$SQL_PASSWORD
      - POSTGRES_DB=$SQL_DATABASE
  redis:
      image: "redis:alpine"
      expose:
        - 6379
      volumes:
        - redis_data:/home/redis/
  nginx:
    image: metr_nginx:elegancy
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server
    volumes:
      - main_server_volume:/home/app/
      - certbot_volume:/var/www/certbot/:ro
      - certbot_certificate_volume:/etc/nginx/ssl/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_volume:/var/www/certbot/:rw
      - certbot_certificate_volume:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  redis_data:
  main_server_volume:
  certbot_volume:
  certbot_certificate_volume:
