# Generated by Django 3.2.8 on 2021-10-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_admin_token_room_access_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='access_token',
        ),
    ]
