# Generated by Django 3.2.8 on 2021-10-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
