# Generated by Django 3.2.8 on 2021-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_client_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
