# Generated by Django 3.2.8 on 2021-10-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='admin_token',
            new_name='access_token',
        ),
    ]
