# Generated by Django 3.2.8 on 2021-10-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='value',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
