# Generated by Django 3.2.8 on 2021-10-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_client_time_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='time_created',
        ),
    ]
