# Generated by Django 3.2.8 on 2021-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211026_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
