# Generated by Django 3.2.8 on 2021-10-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_client_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericanswer',
            name='value',
            field=models.FloatField(),
        ),
    ]
